projects/jpotw/2 bookshorts/bookshorts/models.py
from bookshorts import db #__init__.py 에 있는 db를 갖고온다

#책 정보 저장
class BookInfo(db.Model): #db.Model = 모든 모델의 기본 class
    id = db.Column(db.Integer, primary_key=True) #primary_key를 통해 배타성을 확보
    title = db.Column(db.String(32), nullable=False) #빈값을 허용하고 싶지 않다면 nullable = False로 설정함.
    author = db.Column(db.String(32), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False) #생성 시간
    answer = db.Column(db.String(400), nullable=True)

# GPT 답변 저장
# class Answer(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     bookinfo_id = db.Column(db.Integer, db.ForeignKey('bookinfo.id', ondelete))
#     answer = db.Column(db.String(400), nullable=False)

#회원가입
class Fcuser(db.Model): 
    __tablename__ = 'fcuser'   #테이블 이름 : fcuser : 주로 사용자 정보를 나타내는 클래스
    id = db.Column(db.Integer, primary_key = True)   #id를 프라이머리키로 설정
    password = db.Column(db.String(64))     #패스워드를 받아올 문자열길이 
    userid = db.Column(db.String(32))       #이하 위와 동일
    username = db.Column(db.String(8))

projects/jpotw/2 bookshorts/bookshorts/__init__.py
from flask import Flask, render_template, request, redirect, url_for #render_template으로 html파일 렌더링
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
# from models import db
# from models import Fcuser
import config


db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config.from_object(config) #뭐임 이거? -> config.py를 app.config로 불러오는 거 **get 아니고 from_object**
    app.debug = True

    #ORM
    db.init_app(app)
    migrate.init_app(app,db) #migrate은 뭐하는거
    from . import models
    from .views import main_views, history_views, auth_views, summarize_views
    app.register_blueprint(main_views.bp) #main_views 파일에 bp(blueprint로 만든 객체) 불러오기
    app.register_blueprint(history_views.bp)
    app.register_blueprint(auth_views.bp) 
    app.register_blueprint(summarize_views.bp)  
    return app

projects/jpotw/2 bookshorts/bookshorts/views/auth_views.py
from flask import Blueprint, url_for, render_template, request, session
from werkzeug.security import check_password_hash
from werkzeug.utils import redirect
from ..models import Fcuser

bp = Blueprint('login', __name__, url_prefix='/login')

@bp.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    if request.method == 'POST':
        error=None
        userid = request.form.get('userid')
        password = request.form.get('password')
        print(userid, password)
        if not (userid and password):
            message = "아이디와 비밀번호를 입력해주세요"
            return render_template('login.html', message=message)
        else:
            fcuser = Fcuser.query.filter_by(userid=userid).first()
            if fcuser is None:
                message = "사용자가 존재하지 않습니다"
                return render_template('login.html', message=message)
            elif check_password_hash(fcuser.password, password):
                session['userid'] = userid
                return redirect(url_for('/.bookinfo'))
            else:
                message = "아이디와 비밀번호를 확인해주세요"
                return render_template('login.html', message=message)

projects/jpotw/2 bookshorts/bookshorts/views/history_views.py
from flask import Flask, Blueprint, render_template, url_for
from ..models import BookInfo



bp = Blueprint('history', __name__, url_prefix='/history')


@bp.route('/')
def history():
    book_list = BookInfo.query.order_by(BookInfo.create_date.desc())
    return render_template('book_list/book_list.html', book_list=book_list)


@bp.route('/summarized/<int:id>')
def title(id):
    book=BookInfo.query.get(id)
    return render_template('book_list/summarized.html', book=book)

projects/jpotw/2 bookshorts/bookshorts/views/main_views.py
from flask import Blueprint, render_template, request, redirect, url_for
from bookshorts import db
from ..models import Fcuser
from werkzeug.security import generate_password_hash

#p45 main, __name__, url_prefix를 설정해 줘야 한다고 함. 처음 두 개 뭔지 나중에 확인할 것
bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/')
def login_first():
    return render_template('login.html')



@bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template("register.html")
    else:
        #회원정보 생성 (register html -> python 객체)
        username = request.form.get('username')
        userid = request.form.get('userid') 
        password = request.form.get('password')
        re_password = request.form.get('re_password')
        print(password) # 들어오나 확인해볼 수 있다. 

        if not (username and userid and password and re_password) :
            message = "모두 입력해주세요"
            return render_template('register.html', message=message)
        elif password != re_password:
            message = "비밀번호를 확인해주세요"
            return render_template('register.html', message=message)
        else: #모두 입력이 정상적으로 되었다면 밑에명령실행(DB에 입력됨) (python 객체 -> Database)
            fcuser = Fcuser()
            fcuser.username = username
            fcuser.password = generate_password_hash(password)  #pw을 hash한 상태로 암호화해야 됨       
            fcuser.userid = userid    
            db.session.add(fcuser)
            db.session.commit()
            message = "회원가입 완료"
            return render_template('login.html', message=message)

projects/jpotw/2 bookshorts/bookshorts/views/summarize_views.py
from flask import Blueprint, render_template, request
from ..models import BookInfo
from datetime import datetime
from openai import OpenAI
from dotenv import load_dotenv  
import os
from bookshorts import db


load_dotenv()
openai_api_key=os.getenv('OPENAI_API_KEY')

bp = Blueprint('/', __name__, url_prefix='/')


@bp.route('/bookinfo', methods=['POST', 'GET'])
def bookinfo():
    if request.method == 'GET':
        return render_template('index.html')
    if request.method == 'POST':
        #회원정보 생성 (register html -> python 객체)
        title = request.form.get('title') 
        author = request.form.get('author')
        print(title, author) # 들어오나 확인해볼 수 있다. 

        if (title and author):
         #모두 입력이 정상적으로 되었다면 밑에명령실행(DB에 입력됨) (python 객체 -> Database)
            bookinfo = BookInfo()         
            bookinfo.title = title          
            bookinfo.author = author
            bookinfo.create_date = datetime.now()      
            db.session.add(bookinfo)
            db.session.commit()
        
        book_info = f"{author}의 {title}"
        print(book_info)

        openai = OpenAI(api_key=openai_api_key)
        response = openai.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
            {"role": "system", "content": 
            f'''Don't say; just do
            "당신은 지금부터 책 요약 전문가입니다. 
            저자가 작성한 책의 제목과 저자를 알려주면 당신은 책의 핵심인사이트를 요약합니다.
            {book_info}의 책의 핵심 포인트와 인사이트를 5가지로 요약해주세요."
            '''},
            ]   
        )
        content = response.choices[0].message.content
        for i in range(1, 6):  # Assuming there are up to 5 points
            if f"{i}." in content:
                content = content.replace(f"{i}. ", f"\n{i}. ")
            else: pass
        bookinfo.answer = content
        db.session.add(bookinfo)
        db.session.commit()
        # print(response.choices[0].message.content)
        return render_template('summarize.html', book_info=book_info, content=content) #author, title 정보를 summarize.html로 넘겨줌

projects/jpotw/2 bookshorts/bookshorts/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">    
    {% block css %}{% endblock %}
    <title>{% block title %}{% endblock %} - bookshorts</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

projects/jpotw/2 bookshorts/bookshorts/templates/book_list/book_list.html
{% extends 'base.html' %}

{% block title %}도서 목록{% endblock %}

{% block content %}
{% if book_list %}
    <h1>도서 목록</h1>
    <ul class="book-list">
        {% for book in book_list %}
            <li class="book-item"><a href="/history/summarized/{{ book.id }}">{{ book.title }} - {{ book.author }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>등록된 도서가 없습니다.</p>
{% endif %}
{% endblock %}

projects/jpotw/2 bookshorts/bookshorts/templates/book_list/summarized.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ book.title }} - {{ book.author }}</h1>

<div>
    {{ book.answer }}
</div>
{% endblock %}

projects/jpotw/2 bookshorts/bookshorts/templates/index.html
{% extends 'base.html' %}
    {% block title %} bookshorts {% endblock %}
    {% block css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet">
    {% endblock %}
    {% block content %}
    <div class="container">
        <div class="hero">
            <h1 class="title">bookshorts</h1>
            <h3 class="subtitle">1분에 책 한 권 읽기</h3>
        </div>

        <!-- 시작 화면 (intro) -->
        <div id="intro" class="intro-container">
            <form method="post" action="/bookinfo" onsubmit="start()">
                <h1>bookshorts에 오신 것을 환영합니다! 요약하고 싶은 책을 적어주세요.</h1>
                <div class="input-section">
                    <label for="title">제목</label>
                    <input id="title" name="title">
                </div>
                <div class="input-section">
                    <label for="author">저자</label>
                    <input id="author" name="author">
                </div>
                <div class="button-container">
                    <button type="submit">요약하기</button>
                </div>
            </form>
            </div>
          <!-- Chat 버튼 눌렀을 때  -->
    
        <!-- kakao ad -->
        <div class="kakao-ad">
            <ins class="kakao_ad_area" style="display:none;" data-ad-unit="DAN-KbdwsZ8O86UWMOWU" data-ad-width="320"
                data-ad-height="100"></ins>
            <script type="text/javascript" src="//t1.daumcdn.net/kas/static/ba.min.js" async></script>
        </div>

        <script>

            // Searh 관련 function
            function start() {
                const title = document.getElementById('title').value;
                const author = document.getElementById('author').value;

                if (title === '') {
                    alert('책 제목을 적어주세요!');
                    return;
                }
                if (author === '') {
                    alert('저자의 이름을 적어주세요!');
                    return;
                }    
            }
        </script>
    </div>
    {% endblock %}

projects/jpotw/2 bookshorts/bookshorts/templates/login.html
{% extends "base.html" %}
{% block title %}로그인{% endblock %}
{% block content %}
    <div class="container">
        <div class="login-form">
            <h1 style="text-align: center;">로그인 페이지</h1>
            {% if error %}
                <p>{{ error }}</p>
            {% endif %}
            <form method="POST", action="{{ url_for('login.login') }}" class="input-section">
                <label for="userid">아이디</label>
                <input type="text" id="userid" name="userid" required>
                <label for="password">비밀번호</label>
                <input type="password" id="password" name="password" required>
                <div class="button-container">
                    <button type="submit" class="button">로그인하기</button>
                </div>
            </form>
            <a href="{{ url_for('main.register') }}" class="login-link">회원가입하기</a>
        </div>
    </div>
    <script>
        {% if message %}
            alert("{{ message }}");
        {% endif %}
    </script>
{% endblock %}

projects/jpotw/2 bookshorts/bookshorts/templates/register.html
{% extends "base.html" %}
{% block title %}회원가입{% endblock %}
{% block content %}
<div class="container">
    <div class="login-form">
        <form action="/register" method="post">
            <div class="input-section">
                <label for="username">이름</label>
                <input type="text" name="username" id="username" class="input-section input">
            </div>
            <div class="input-section">
                <label for="userid">아이디</label>
                <input type="text" name="userid" id="userid" class="input-section input">
            </div>
            <div class="input-section">
                <label for="password">비밀번호</label>
                <input type="password" name="password" id="password" class="input-section input">
            </div>
            <div class="input-section">
                <label for="password2">비밀번호 확인</label>
                <input type="password" name="re_password" id="re_password" class="input-section input">
            </div>
            <div class="button-container">
                <button type="submit" class="button-container button" style="text-align: center;">회원가입하기</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

projects/jpotw/2 bookshorts/bookshorts/templates/summarize.html
{% extends 'base.html' %}
{% block title %} {{ book_info }} 요약 {% endblock %}
{% block content %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
            integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="shortcut icon" href="favicon.ico">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet">
      <style>
         body {
        background: #007BFF;  /* fallback for old browsers */
        background: -webkit-linear-gradient(to right, #0062E6, #33AEFF);  /* Chrome 10-25, Safari 5.1-6 */
        background: linear-gradient(to right, #0062E6, #33AEFF); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        color: #fff;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        font-family: 'Poppins', sans-serif;
    }
        </style>
    <div id="chat" class="chat-container">
        <div class="chat-box">
            <form method="post" action="/summarize">            
                <div class="chat-message assistant-welcome">
                <p class="assistant">{{ book_info }}에서의 핵심 내용을 요약하겠습니다:
                    {{ content }}
                </p>
                </div>
        </div>
    </div>
        
{% endblock %}