projects/jpotw/3.insight_finder/vs/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    app.debug = True

    from .views import main_views
    app.register_blueprint(main_views.bp)
    return app

projects/jpotw/3.insight_finder/vs/views/main_views.py
from flask import Blueprint, render_template, request
from langchain.vectorstores.chroma import Chroma
from dotenv import load_dotenv
from langchain.embeddings.huggingface import HuggingFaceEmbeddings    
import os
from langchain_openai import ChatOpenAI
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain.chains import RetrievalQA
from langchain.chat_models import ChatOpenAI


#openai api key
load_dotenv()
openai_api_key=os.getenv("OPENAI_API_KEY")
llm = ChatOpenAI(openai_api_key=openai_api_key,
                    model_name="gpt-3.5-turbo", 
                    streaming=True, 
                    callbacks=[StreamingStdOutCallbackHandler()],
                    temperature=0
                 )
embeddings=HuggingFaceEmbeddings()
db=Chroma(
    persist_directory="vs/huggingface2",
    embedding_function=embeddings
)

bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/', methods=['GET', 'POST'])
def answer():
    if request.method == 'POST':
        question = request.form.get('question') #html에서 name="question"인 것을 가져옴

        #RetrievalQA chain 만들기
        qa = RetrievalQA.from_chain_type(llm=llm,
                                 chain_type="stuff", #4가지 체인 방식중 가장 심플한
                                 return_source_documents=True, #참고문헌 표시
                                 retriever=db.as_retriever(         #db를 retriever 검색기로 이용하겠다는 뜻
                                     search_type="mmr", #다양한 소스 참고
                                     search_kwargs={'k':3, 'fetch_k':10})#fetch_k 후보군 총개수
                                 )
        result = qa(question)
        ai_answer = result['result']
        print(ai_answer)
        source_document = result['source_documents']
        print(source_document)
        resource = []
        for document in source_document:
            resource.append(document.page_content)
        print(resource)
        return render_template('answer.html', question=question, ai_answer=ai_answer, resource=resource)
    
    else:
        return render_template('main.html')

projects/jpotw/3.insight_finder/vs/templates/answer.html
{% extends "base.html" %}
{% block title %}관련 문서 페이지{% endblock %}
{% block content %}
    <div class="container py-5 text-center">
        <h1 class="display-4 text-purple">질문: {{ question }}</h1>
        <div class="chat-container">
            <div class = "answer-container">
            {{ ai_answer }}
            </div>
            <h2 class="display-4 text-purple">관련 문서</h2>
            <div class="chat-box">
                {% for r in resource %}
                    <div class="chat-message assistant">
                        {{ r }}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

projects/jpotw/3.insight_finder/vs/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    {% endblock %}
    <title>{% block title %}{% endblock %} - insight finder</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

projects/jpotw/3.insight_finder/vs/templates/main.html
{% extends "base.html" %}
{% block title %}질문 페이지{% endblock %}
{% block content %}
    <div class="question-container">
        <div class="question-form">
            <form method="POST", action="{{ url_for('main.answer') }}">
                <div class="input-section">
                    <label for="question">질문</label>
                    <input type="str" id="question" name="question" required>
                </div>
                <div>
                    <button type="submit" class="button">질문하기</button>
                </div>
            </form>        
        </div>
    </div>
{% endblock %}